# stages:
#   - build
#   - test
#   - deploy
#   - .post

variables:
  UV_VERSION: "0.9"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy
  UV_CACHE_DIR: .uv-cache
  KERAS_BACKEND: "torch"

default:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR

build-changelog:
  stage: build
  image:
    name: orhunp/git-cliff:latest
    entrypoint: [""]
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
  script:
    - git-cliff -r . > CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-package:
  stage: build
  script:
    - uv build
  after_script:
    - uv cache prune --ci
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
      changes:
        - src/softadapt/**/*

build-docs:
  stage: build
  script:
    - uv run --dev --with pdoc $CI_PROJECT_DIR/scripts/make_docs.py
  after_script:
    - uv cache prune --ci
  variables:
    PDOC_ALLOW_EXEC: 1
  artifacts:
    paths:
      - docs/**/*.md
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch

test-package:
  stage: test
  script:
    - uv run --with pytest --with pytest_cov --dev pytest --cov-report=xml:cov.xml --junitxml=report.xml
  after_script:
    - uv cache prune --ci
  needs:
    - build-package
  coverage: '/TOTAL.*? (100(?:\.0+)?\%\\|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
      changes:
        - src/softadapt/**/*
        - tests/**/*

deploy-docs:
  stage: deploy
  image: 
    name: alpine/git:latest
    entrypoint: [""]
  variables:
    WIKI_URL: ${CI_SERVER_PROTOCOL}://project_${CI_PROJECT_ID}_bot:${WIKI_WRITE_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_PATH}.wiki.git
  dependencies:
    - build-docs
  needs:
    - job: build-docs
  script:
    - cd ..
    - git clone "${WIKI_URL}"
    - git -C ${CI_PROJECT_NAME}.wiki config user.name "$GITLAB_USER_NAME"
    - git -C ${CI_PROJECT_NAME}.wiki config user.email "$GITLAB_USER_EMAIL"
    - cp -r ${CI_PROJECT_NAME}/docs/* ${CI_PROJECT_NAME}.wiki
    - '[ -z "$(git -C ${CI_PROJECT_NAME}.wiki status --porcelain)" ] && exit 0'
    - git -C ${CI_PROJECT_NAME}.wiki add .
    - git -C ${CI_PROJECT_NAME}.wiki commit -am "Updated triggered from $CI_COMMIT_SHORT_SHA $CI_COMMIT_MESSAGE" && git -C ${CI_PROJECT_NAME}.wiki push origin master || true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch

deploy-changelog:
  stage: deploy
  image:
    name: alpine/git:latest
    entrypoint: [""]
  dependencies:
    - build-changelog
  needs:
    - job: build-changelog
  before_script:
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
  script:
    - '[ -z "$(git status --porcelain)" ] && exit 0'
    - git add CHANGELOG.md
    - 'git commit --no-verify -m "docs(CHANGELOG.md): refresh changelog with new commits from $CI_COMMIT_SHORT_SHA"'
    - git push $CI_REPOSITORY_URL HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH