# stages:
#   - build
#   - test
#   - deploy
#   - .post

variables:
  UV_VERSION: "0.9"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy
  UV_CACHE_DIR: .uv-cache
  KERAS_BACKEND: "torch"

default:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR

uv-build:
  stage: build
  script:
    - uv build
  artifacts:
    paths:
      - "dist/"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch

unittest:
  stage: test
  script:
    - uv run --with pytest --with keras --with torch --with pytest_cov pytest --cov-report=xml:cov.xml --junitxml=report.xml
  variables:
    UV_INDEX: "pytorch=https://download.pytorch.org/whl/cpu uv lock"
  coverage: '/TOTAL.*? (100(?:\.0+)?\%\\|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch

post-step:
  stage: .post
  script:
    - uv cache prune --ci
  rules:
    - when: always